#!/bin/bash 
cd ~/.config/
cp -r alacritty fish neofetch ranger sxhkd zathura htop mpv paru starship.toml vlc dmscripts i3 pcmanfm styli.sh yay sxiv mimeapps.list /home/omar/github/dotfiles/config
cd /home/omar/github/dotfiles/config/dmscripts
rm dmnote
cp -r /home/omar/scripts/* /home/omar/github/dotfiles/scripts 
cp ~/.config/qutebrowser/quickmarks ~/.config/qutebrowser/config.py ~/github/dotfiles/config/qutebrowser
cp -r ~/.local/share/qutebrowser/userscripts ~/github/dotfiles/config/qutebrowser/
cp ~/.config/ncmpcpp/config ~/github/dotfiles/config/ncmpcpp
cp ~/.config/ncmpcpp/bindings ~/github/dotfiles/config/ncmpcpp
cp ~/.config/mpd/mpd.conf ~/github/dotfiles/config/mpd
cp ~/.config/mpDris2/mpDris2.conf ~/github/dotfiles/config/mpDris2
cp -rf ~/.config/nnn/plugins ~/github/dotfiles/config/nnn
cp -rf ~/.config/kitty/kitty.conf ~/github/dotfiles/config/kitty

